add normalizer that leaved conjugation
WorksApplications/SudachiTra pull request #31
Opened 2021-12-10 02:01 UTC by katsutan

2021-12-10 02:30 UTC, eiennohito requested changes
1. Using string concatenation in the hot path is very bad for execution speed, do not do it. Use tuples for keys instead.
2. Call Morpheme methods only once. (this should be fixed eventually in SudachiPy, but for the time being)
3. Try to use 0.6.2 and its PosMatcher infrastructure, prefer using `get_part_of_speech_id()` instead of `get_part_of_speech()`
4. Tables should not be jsons, they should be Python files. Generating those Python files from JSON is OK.
5. Organize filters in multiple levels, first level should do simple blacklist lookup, second level should

2021-12-10 02:30 UTC, eiennohito commented on sudachitra/normalizer_leaved_conjugation.py
> +        pos = list(morpheme.part_of_speech())
you don't need list here, tuple will work perfectly well

2021-12-10 02:50 UTC, eiennohito commented
Also, typo: inflectoin_table.json  -> inflection_table.json

2021-12-13 02:40 UTC, eiennohito commented on sudachitra/normalizer_leaved_conjugation.py
> +        if not self.is_conjugative_pos(morpheme) or not self.is_needs_inflection(morpheme):
this should be one operation instead of two

2021-12-15 02:10 UTC, eiennohito approved these changes
LGTM, thanks for fixes

2021-12-17 10:27 UTC, t-yamamura commented
It would be helpful to have some more comments and documents on `NormalizerLeavedConjugation`.
In particular, since `NormalizerLeavedConjugation` is a WORD_FORM_TYPE that does not exist in SudachiPy, so it helps understanding to explain how it differs from the usual normalization process.

2021-12-21 09:21 UTC, merged