Feature/use huggingface compatible pretokenizer
WorksApplications/SudachiTra pull request #38
Opened 2022-01-20 08:18 UTC by t-yamamura

2022-01-21 00:13 UTC, eiennohito requested changes
Also please add tests for correct token mapping logic (if I am wording that correctly).

2022-01-21 00:13 UTC, eiennohito commented on sudachitra/pretokenizer/japanese_bert_wordpiece_tokenizer.py
> +            os.environ["TOKENIZERS_PARALLELISM"] = "false"
This will switch parallelism off for all further calls into tokenizers, not just for this training call. This should be done in another level (with added comments on caveats for this logic)

2022-01-21 00:13 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +            _ = [ns.replace(ns.normalized, _word_formatter(m)) for ns, m in zip(normalized_strings, morphemes)]
Doing side effect operation in a list comprehension is fishy. Replace this with a simple for loop.

2022-01-21 00:13 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +    return [normalized_string[start:end] for token_span in token_spans for start, end in token_span]
This should be done with `morpheme.begin()`/`morpheme.end()` methods. If this can't be done with them it should be an issue in Sudachi.rs project. Don't be afraid to request new APIs if nothing works and you need write a workaround.

2022-01-21 00:13 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +            _ = [ns.replace(ns.normalized, _word_formatter(m)) for ns, m in zip(normalized_strings, morphemes)]
Also it won't work correctly if `len(normalized_strings) != len(morphemes)`

2022-01-21 00:13 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +    return _handler
The `_handler` should be `None` for surface-only processing. As I understand the code, you are trying to delete zero-width morphemes which is not a current behavior of the built-in `PreTokenizer` implementation. That should be an issue of Sudachi.rs.

2022-01-21 00:14 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +            _ = [ns.replace(ns.normalized, _word_formatter(m)) for ns, m in zip(normalized_strings, morphemes)]
Also need to have comments on the fact that this logic handles token mapping from the original string.

2022-01-21 10:16 UTC, t-yamamura commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +    return [normalized_string[start:end] for token_span in token_spans for start, end in token_span]
https://github.com/WorksApplications/SudachiTra/pull/38/commits/1b818ea4308b224ebc4c25b194b9d9b4906073c3

2022-01-21 11:15 UTC, t-yamamura commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +    return _handler
As you mentioned, it is inherently sufficient for the `preokenizer_handler()` to return `None` for surface-only processing.
However, because of this issue (https://github.com/WorksApplications/SudachiPy/issues/160), this function needs to  delete zero-width morphemes as postprocessing.

2022-01-21 11:20 UTC, t-yamamura commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +    return _handler
```python
>>> from sudachipy import Dictionary, SplitMode
>>> 
>>> sudachi_dict = Dictionary(dict='core')
>>> sudachi = sudachi_dict.create(SplitMode.C)
>>>
>>> s = "İstanbul の表記にはドットが付いたİが使われる"
>>> sudachi.tokenize(s2)
<MorphemeList[
  <Morpheme(İstanbul, 0:8, (-1, 3))>,
  <Morpheme( , 8:9, (0, 0))>,
  <Morpheme(の, 9:10, (0, 119622))>,
  <Morpheme(表記, 10:12, (0, 663713))>,
  <Morpheme(に, 12:13, (0, 114113))>,
  <Morpheme(は, 13:14, (0, 122101))>,
  <Morpheme(ドット, 14:17, (0, 226684))>,
  <Morpheme(が, 17:18, (0, 45381))>,
  <Morpheme(付い, 18:20, (0, 286231))>,
  <Morpheme(た, 20:21, (0, 83862))>,
  <Morpheme(İ, 21:22, (-1, 3))>,
  <Morpheme(, 22:22, (-1, 2))>,
  <Morpheme(が, 22:23, (0, 45381))>,
  <Morpheme(使わ, 23:25, (0, 294817))>,
  <Morpheme(れる, 25:27, (0, 169355))>,
]>
````

2022-01-21 11:46 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +    return _handler
I've fixed İstanbul, as you can see (and also complex emoji as well), but plain İ still produces zero-width token. I see, that's a bug.

2022-01-21 11:53 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +            _ = [ns.replace(ns.normalized, _word_formatter(m)) for ns, m in zip(normalized_strings, morphemes)]
Still, this whole logic should be refactored to a for loop constructing a resulting list.

2022-01-21 11:53 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +    return [normalized_string[start:end] for token_span in token_spans for start, end in token_span]
Not really, see the comment of `_handler`

2022-01-24 07:02 UTC, t-yamamura commented on sudachitra/pretokenizer/japanese_bert_wordpiece_tokenizer.py
> +            os.environ["TOKENIZERS_PARALLELISM"] = "false"
fixed by https://github.com/WorksApplications/SudachiTra/pull/38/commits/b213c8dcb0402cf68c767aca73d0973dc756a73b

2022-01-24 07:18 UTC, t-yamamura commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +    return _handler
Some characters that are split into multiple characters are parsed as morphemes containing empty characters in sudachipy.
(This issue can be avoided by applying NFKC to the preprocessing of the input text.)

```python
echo "…" | sudachipy                   
…	補助記号,句点,*,*,*,*	.
	補助記号,句点,*,*,*,*	.
	補助記号,句点,*,*,*,*	.
EOS
```

2022-01-24 07:39 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +    return _handler
I am aware of that phenomenon, however in this case there shouldn't be a zero-width morpheme here.

2022-01-24 09:17 UTC, t-yamamura commented on sudachitra/pretokenizer/japanese_bert_wordpiece_tokenizer.py
> +            os.environ["TOKENIZERS_PARALLELISM"] = "false"
I rewrote code to not control environment variables in class JapaneseBertWordPieceTokenizer.　https://github.com/WorksApplications/SudachiTra/pull/38/commits/32cf99ca52454f6b03708c9695eb8eaabe49237c

2022-01-25 03:13 UTC, t-yamamura commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +            _ = [ns.replace(ns.normalized, _word_formatter(m)) for ns, m in zip(normalized_strings, morphemes)]
fixed by https://github.com/WorksApplications/SudachiTra/pull/38/commits/5375aa167757e75434e6faa41adba88f0a4a2b62

2022-01-25 04:45 UTC, eiennohito requested changes

2022-01-25 04:45 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +            for ns, m in zip(normalized_strings, morphemes):
zip is incorrect when `len(morphemes) != len(normalized_strings)

2022-01-25 04:45 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +            for ns, m in zip(normalized_strings, morphemes):
This must be a *single* loop, not two loops.

2022-01-25 04:45 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +            for ns, m in zip(normalized_strings, morphemes):
`m.surface() != ''` can also be written as `len(m) != 0`, but in this case there are already `m.begin()` and `m.end()` calls.

So it can be done something like this:

```
result = []
for m in morphemes:
  b = m.begin()
  e = m.end()
  if b == e: # empty token
    continue
  token = original[b:e]
  if _word_formatter is not None:
    token.replace(token.normalized, _word_formatter(m))
  result.append(token)
return result
```

Note that this code tries to avoid unnecessary computations. PreTokenizer handler is a performance-critical component and unnecessary calls should be avoided here

2022-01-25 04:45 UTC, eiennohito commented on setup.py
> +        "pytextspan>=0.5.4",
this also should be deleted

2022-01-25 06:24 UTC, t-yamamura commented on setup.py
> +        "pytextspan>=0.5.4",
fixed by https://github.com/WorksApplications/SudachiTra/pull/38/commits/fb737c87d3da9b1b168c64e72d0994622efc20a5

2022-01-25 06:36 UTC, t-yamamura commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +            for ns, m in zip(normalized_strings, morphemes):
I agree with your proposal from a performance of view. https://github.com/WorksApplications/SudachiTra/pull/38/commits/64df1cde548c31b326b0cb961a601f9c462f3665

My only concern is that there is the if statement in each iteration.
To avoid this, we could use an if statement before the loop, but I think that would be redundant (even though the performance is almost the same).
What do you think?

2022-01-25 06:50 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +            for ns, m in zip(normalized_strings, morphemes):
The best way would be probably to emit different handler functions depending on the condition. That probably can be overkill (or you can try and measure, that can be a nice learning experience as well).
My comments on the performance were more related to calling `m.surface()`, which creates a string object, allocating memory, for each call.
Comparison to `None` should be cheaper, but you can measure it.

2022-01-25 06:52 UTC, eiennohito commented on sudachitra/pretokenizer/sudachipy_pretokenizer.py
> +            for ns, m in zip(normalized_strings, morphemes):
Also, your previous version was incorrect in case of mismatching lengths of `MorphemeList` and tokens so creating a token and calling replace should share a single condition anyway.

2022-01-25 07:04 UTC, eiennohito approved these changes

2022-01-26 08:54 UTC, t-yamamura commented
> Also please add tests for correct token mapping logic (if I am wording that correctly).

I added these tests (https://github.com/WorksApplications/SudachiTra/pull/38/commits/66afb37e3d4dadd4172dc44c24690008b54f5511), except for the ones that can't be tested now due to (https://github.com/WorksApplications/SudachiTra/issues/42).

2022-01-27 07:27 UTC, merged